name: tierrating
services:

  server:
    image: ghcr.io/tierrating/tierrating:latest
    restart: unless-stopped
    ports:
      - 8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: tierrating
      DB_PASSWORD: CHANGE_THIS
      ANILIST_CLIENT_KEY:
      ANILIST_CLIENT_SECRET:
      ANILIST_REDIRECT_URL: http://localhost:3000/auth/anilist
      TRAKT_CLIENT_KEY:
      TRAKT_CLIENT_SECRET:
      TRAKT_REDIRECT_URL: http://localhost:3000/auth/trakt

  ui:
    image: ghcr.io/tierrating/tierrating-ui:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      API_URL: 'http://server:8080'
      ANILIST_CLIENT_ID:
      TRAKT_CLIENT_ID:

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tierrating
      POSTGRES_PASSWORD: CHANGE_THIS
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
